### ISSUE TITLE
Review Final Test Internship

### ISSUE THREAD

**Issue by kingfariz** [Agnesty/techtest_phase1_agnesty#5]
Berikut adalah kriteria score pada final test ini.

**(up to +5) Aplikasi dapat melakukan fitur login**
Review: Aplikasi berhasil melakukan fitur login
**Nilai 5**

**(up to +7) User yang telah login dapat melakukan aksi Create, Update, Delete pada halaman produk yang telah dibuat pada techtest phase 2**
Review: Aplikasi memiliki fitur CRUD
**Nilai 7**

**(up to +5) Memiliki User Interface Yang cukup menarik**
Review: Aplikasi memiliki fitur CRUD
**Nilai 5**

**(up to +5) Kerapihan code: structure code(state management, controller, widget, screen) per fitur (dapat melihat contoh code pada referensi code dibawah)**
Review: 
A. Code sudah dibagi per jenis tetapi Code tidak dibagi perfitur, ini dapat membuat development (team) sulit dalam mengelola code. Dalam big scale application dengan tim yang banyak biasanya dibagi per fitur bukan per jenis file, namun kembali lagi struktur code biasanya ditentukan oleh techlead/senior. Berikut adalah contohnya:
1. penjelasan clean architecture https://devmuaz.medium.com/flutter-clean-architecture-series-part-1-d2d4c2e75c47
2. example implementasi clean architecture https://github.com/ydhnwb/flutter-clean-architecture/tree/main
3. example game hunter app (hasil project dari technical test senior flutter) https://github.com/kingfariz/game_hunter/tree/main/lib

B. Saat Run aplikasi masih banyak terjadi uncaught exception dan saat register dengan email sama bisa mendapat pesan error namun tetap masuk kedalam aplikasi. 
**Nilai 2**

(up to +3) Aplikasi memiliki session, jika AFK selama 1 menit maka akan muncul pop up atau dialog untuk login kembali. Popup tidak dapat di close (barrierdismissable = false)
Review: Aplikasi memiliki session expired namun masih ada beberapa test case yang failed
1. Waktu tidak 1 menit
2. Popup bisa muncul beberapa kali (meniban popup lainnya)
3. Counter session timeout tidak dimulai dari pertama berhasil login, namun saat menekan sesuatu di layar saat sudah login timer baru berjalan
4. Ketika sudah mendapat poup AFK, dan menekan screen counter start kembali sehingga dialog bisa muncul berkali kali.
**Nilai 1**

(up to +5) Password Login melalui aplikasi dikirim ke database dalam bentuk sudah ter-enkripsi. Jika data sama, maka user dapat login.
Review: Aplikasi sudah memiliki enkripsi.
**Nilai 5**

Total Nilai: 25 + 60 (Nilai Phase 1 - 3) = 95 (A)

**Comment by kingfariz** [comment]
Terimakasih telah menyelesaikan program internship & bootcamp dari PT ARI. Semoga Ilmu yang didapat dapat berguna kedepannya.

Jika ada pertanyaan atau ingin diskusi seputar IT boleh disampaikan melalui grup discord.

**Comment by Agnesty** [comment]
Terima kasih kak atas penilaiannya. Untuk sertifikatnya bagaimana kak 🙏

Pada tanggal Sen, 10 Jul 2023 15.12, kingfariz ***@***.***>
menulis:

**Comment by kingfariz** [comment]
Untuk sertifikat sedang di proses mba, saya usahakan akan kirim hari minggu mendatang

**Comment by Agnesty** [comment]
Baik kak terima kasih banyak 🙏

Pada tanggal Sel, 11 Jul 2023 14.45, kingfariz ***@***.***>
menulis:
